### ISSUE TITLE
MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by falcon56321** [Xictul/OmegaBot#16]
I have installed the modules, but I am getting such an error, can you help?

![image](https://user-images.githubusercontent.com/34168507/216314554-4a267f48-bce4-402c-b82e-029270a72036.png)

**Comment by Xictul** [comment]
What are you trying to do in the first place? Like what command did you run. Also please attach a screenshot of your package.json file.

**Comment by falcon56321** [comment]
![image](https://user-images.githubusercontent.com/34168507/216321082-2001dbb0-bd99-4b28-9241-12bf559abfa4.png)
![image](https://user-images.githubusercontent.com/34168507/216321109-3c92dac9-8012-4899-a37f-da1a67573d23.png)

**Comment by Xictul** [comment]
That's because our Database keys and login Tokens are only available to developers of the bot. To become a developer and work on the bot, you can contact us in our Discord: https://omegabot.xyz/discord

**Comment by falcon56321** [comment]
I want to integrate and use your project on my own website, but I

**Comment by Xictul** [comment]
What is the link to your website and what do you plan to do with our project? Also if you have a Discord account I'd much rather use a support ticket in our server to handle this.

**Comment by falcon56321** [comment]
Your discord link has expired

**Comment by falcon56321** [comment]
![image](https://user-images.githubusercontent.com/34168507/216328194-9376ca09-a4ba-4676-9ea4-e0a77c03df04.png)

**Comment by Xictul** [comment]
Ah okay, my bad. Here's a new link: https://discord.gg/enGBYEvW6s
